#!/bin/sh

echo XX $* $#

[ $# -lt 2 ] && { echo "Usage: test <display> <key> [<key> ...]"; exit 1; }

display=$1

shift

{ 
  for key in $*; do
	  echo "KeyStrPress $key"
		echo "KeyStrRelease $key"
  done
} | xmacroplay "$display"
